apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Configuration
metadata:
  name: custom-config
spec:
  # namespace: test
  timeouts:
    apply: 300s
    assert: 400s
    cleanup: 120s
    delete: 120s
    error: 180s
    exec: 300s
  skipDelete: false
  # skipDelete: true
  failFast: true
  parallel: 1
